apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-deployment
  labels:
    app: my-hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-hello
  template:
    metadata:
      labels:
        app: my-hello
    spec:
      containers:
      - name: my-hello
        image: my-registry.local:5000/my-hello:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-hello-nodeport
  labels:
    app: my-hello
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    targetPort: 8080
    protocol: TCP
  selector:
    app: my-hello
